import React from "react";

export default function ViewUsers() {
  return (
    <>
      <table className ="table">
        <tr>
          <td>Id</td>
          <td>Username</td>
          <td>Email</td>
          <td>Role</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Id</td>
          <td>Username</td>
          <td>Email</td>
          <td>Role</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Id</td>
          <td>Username</td>
          <td>Email</td>
          <td>Role</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Id</td>
          <td>Username</td>
          <td>Email</td>
          <td>Role</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Id</td>
          <td>Username</td>
          <td>Email</td>
          <td>Role</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Id</td>
          <td>Username</td>
          <td>Email</td>
          <td>Role</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Id</td>
          <td>Username</td>
          <td>Email</td>
          <td>Role</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Id</td>
          <td>Username</td>
          <td>Email</td>
          <td>Role</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Id</td>
          <td>Username</td>
          <td>Email</td>
          <td>Role</td>
          <td>Actions</td>
        </tr>
        <tr>
          <td>Id</td>
          <td>Username</td>
          <td>Email</td>
          <td>Role</td>
          <td>Actions</td>
        </tr>
      </table>
    </>
  );
}
